# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d2783337ac7d49db7f2c012d0684c66237f7026d8dfd6fd7e51064b8c34e04251fe7b123d34124e221e835bbdb59da1bb064c470db90cedafa0201388dfdb52

test:
  secret_key_base: 084376da18200f58dd538356a354ba4674e551df7630492ab452d2660672f2257e5329c2ef74e634a9731914d42f6413119109186abf5d59751fe9a1ac3ec1f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
